<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<title>Data URI for IE6+</title>
  <!--[if lt IE 8]><script type="text/javascript" src="datauri.js" defer="defer"></script><![endif]-->
	<style type="text/css">
		body {
			font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
			font-size: 11px;
		}
		div {
			margin-bottom: 2em;
		}
		h1 {
			background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKwAAAABCAMAAAB0bbXaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAwBQTFRFAAAABwkIAQASEwIKAEpKO0t8azs5ezo4S2mniA8isgABvQoQszNCxzpCyEpWzVpphI1wwbV74aR7vrSDjMT%2Fmcz%2FxrSEy7iN7aeFx8ys18ah%2F%2F%2BZxMXHzP%2F%2F1v%2F77e7C%2F%2FfW%2F%2F%2F%2FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmwGzrwAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjM2qefiJQAAAGRJREFUGFdNy0kWgCAMA9AqKggooDgADnj%2FS9qy0b9KXlM4nLsz2cJ1hVhitE1jZ9T9rCicJFBkUGgtpdJQY%2Bz3nJNB6flM2AdJFJ3MCMCqVnjOuW8Lj%2BPFo9%2FXSR0ntCoELY8XJmIL6Cdxy7EAAAAASUVORK5CYII%3D);
			color: #0c0;
			font-size: 2em;
			font-weight: bold;
		}
	</style>
</head>
<body>
		
<h2>Images</h2>
<p>
<?php
$files = glob('./img/*');

$i = isset($_GET['img']) ? intval($_GET['img']) : 100;
foreach($files as $file){
	if (!$i--) break;
	echo '<img  id="'.basename($file, '.png').'" src="data:image/png;base64,'.base64_encode(file_get_contents($file))."\" />\n";
}
?>
</p>

<h2>Background:</h2>
<p>
	<h1>WOOOW !</h1>
</p>

<h2>Links:</h2>
<p>
	<a href="data:text/html;base64,VGhpcyBpcyBhIHRlc3QK">Link test !</a>
</p>

</body>
</html>